"""productId-on-reviewsys

Revision ID: 599121002315
Revises: e4d328fd924b
Create Date: 2026-04-20 16:39:09.530501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599121002315'
down_revision = 'e4d328fd924b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_reviews_product_id', 'products', ['productId'], ['productId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('productId')

    # ### end Alembic commands ###
